-- ============================================================================
-- WASTE MANAGEMENT DATABASE - RELATIONSHIP SUMMARY & DOCUMENTATION
-- ============================================================================

DATABASE: wasteManagemet
TOTAL TABLES: 11
TOTAL RELATIONSHIPS: 12 (10 Binary + 2 Ternary)

-- ============================================================================
-- RELATIONSHIP MAPPING & TYPES
-- ============================================================================

BINARY RELATIONSHIPS (One-to-Many or Many-to-One):
============================================================

1. Citizen ↔ Area
   Cardinality: Many Citizens to One Area
   Foreign Key: Citizen.area_id → Area.area_id
   Type: Mandatory to Optional
   Purpose: Defines which area a citizen resides in

2. Citizen ↔ Bill
   Cardinality: One Citizen to Many Bills
   Foreign Key: Bill.citizen_id → Citizen.citizen_id
   Type: Mandatory to Mandatory
   Purpose: Tracks billing for each citizen

3. Citizen ↔ Waste
   Cardinality: One Citizen to Many Waste Records
   Foreign Key: Waste.citizen_id → Citizen.citizen_id
   Type: Mandatory to Mandatory
   Purpose: Tracks waste generated by citizens

4. Citizen ↔ Payment
   Cardinality: One Citizen to Many Payments
   Foreign Key: Payment.citizen_id → Citizen.citizen_id
   Type: Mandatory to Mandatory
   Purpose: Tracks payments made by citizens

5. Area ↔ Bins
   Cardinality: One Area to Many Bins
   Foreign Key: Bins.area_id → Area.area_id
   Type: Mandatory to Mandatory
   Purpose: Assigns waste bins to specific areas

6. Area ↔ Crew
   Cardinality: One Area to Many Crew Members
   Foreign Key: Crew.area_id → Area.area_id
   Type: Mandatory to Mandatory
   Purpose: Assigns crew members to areas for waste collection

7. Area ↔ Collection_Schedule
   Cardinality: One Area to Many Schedules
   Foreign Key: Collection_Schedule.area_id → Area.area_id
   Type: Mandatory to Mandatory
   Purpose: Defines collection schedules for each area

8. Area ↔ Assigned (Teams)
   Cardinality: One Area to Many Teams
   Foreign Key: Assigned.area_id → Area.area_id
   Type: Mandatory to Mandatory
   Purpose: Assigns teams to specific areas

9. Bill ↔ Payment
   Cardinality: One Bill to Many Payments
   Foreign Key: Payment.bill_id → Bill.bill_id
   Type: Mandatory to Mandatory
   Purpose: Tracks multiple partial/full payments for a bill

10. Waste ↔ Recycling_Center
    Cardinality: One Waste Type to One Recycling Center
    Foreign Key: Recycling_Center.waste_id → Waste.waste_id
    Type: Mandatory to Optional
    Purpose: Routes waste to appropriate recycling centers


TERNARY RELATIONSHIPS (3+ Tables):
============================================================

TERNARY 1: Has_Schedule (Area ↔ Crew ↔ Collection_Schedule)
   Junction Table: Has_Schedule
   Connected Tables: Area, Crew, Collection_Schedule
   Foreign Keys:
      - Has_Schedule.area_id → Area.area_id
      - Has_Schedule.crew_id → Crew.crew_id
      - Has_Schedule.schedule_id → Collection_Schedule.schedule_id
   Unique Constraint: (area_id, crew_id, schedule_id)
   Purpose: Links crew members to specific areas with their collection schedules
   Example: Crew A is assigned to Area X on Schedule Y
   
   Structure:
   Crew (crew_id, crew_name, area_id, schedule_id, team_id)
        ↓
   Has_Schedule (has_schedule_id, area_id, crew_id, schedule_id)
        ↓
   Collection_Schedule (schedule_id, schedule_date, area_id)
        ↓
   Area (area_id, area_name)

TERNARY 2: Assigned (Crew ↔ Area ↔ Team)
   Note: This is actually a binary relationship with Team through Crew
   Connected Tables: Crew, Assigned, Area
   Foreign Keys:
      - Assigned.area_id → Area.area_id
      - Assigned.team_id ← Crew.team_id (referenced by)
      - Crew.team_id → Assigned.team_id
   Unique Constraint: UNIQUE (area_id, team_id)
   Purpose: Assigns crews to teams in specific areas
   Example: Team A is assigned to Area X with multiple crew members
   
   Structure:
   Crew (crew_id, crew_name, team_id, area_id)
        ↓
   Assigned (team_id, team_name, area_id)
        ↓
   Area (area_id, area_name)


-- ============================================================================
-- JOIN TYPES USED IN QUERIES
-- ============================================================================

INNER JOIN:
- Used when you need data from BOTH tables (both sides must have matching records)
- Example: Get bills with their payments (only bills that have payments)
- Common in: Citizen-Bill, Bill-Payment, Waste-Recycling_Center

LEFT JOIN:
- Used when you want ALL records from left table, matching records from right table
- Example: Get all citizens with their bills (show citizens even if they have no bills)
- Common in: Area-Citizen, Area-Bins, Citizen-Waste

FULL OUTER JOIN:
- Not commonly used in MySQL (use UNION of LEFT and RIGHT JOINs)
- Would show all records from both tables


-- ============================================================================
-- KEY QUERY PATTERNS
-- ============================================================================

PATTERN 1: Get One Record with All Related Data
   Citizen → Area (residence)
           → Bills → Payments (financial)
           → Waste → Recycling_Center (disposal)
   
   Query: Multiple JOINs + GROUP BY for aggregates

PATTERN 2: Get All Records of One Type with Summary
   Area → Citizens (count, names)
       → Bins (count, fill levels)
       → Crew (count, names)
       → Schedules (count, dates)
   
   Query: Multiple LEFT JOINs + GROUP BY + COUNT/SUM

PATTERN 3: Ternary Relationship Resolution
   Has_Schedule requires joining 4 tables:
   Has_Schedule → Area + Crew + Collection_Schedule
   
   Assigned requires joining 3 tables:
   Assigned → Area + Crew (via team_id)


-- ============================================================================
-- SAMPLE DATA FLOW
-- ============================================================================

Step 1: Create Area
   INSERT INTO Area (area_name) VALUES ('Downtown')

Step 2: Create Citizens in Area
   INSERT INTO Citizen (name, area_id) VALUES ('John', 1)

Step 3: Create Bins in Area
   INSERT INTO Bins (area_id, status) VALUES (1, 'Empty')

Step 4: Create Team for Area
   INSERT INTO Assigned (team_name, area_id) VALUES ('Team A', 1)

Step 5: Create Crew in Team
   INSERT INTO Crew (crew_name, area_id, team_id, schedule_id) 
   VALUES ('Crew 1', 1, 1, 1)

Step 6: Create Collection Schedule
   INSERT INTO Collection_Schedule (schedule_date, area_id) 
   VALUES ('2025-11-15', 1)

Step 7: Link Schedule to Crew
   INSERT INTO Has_Schedule (area_id, crew_id, schedule_id) 
   VALUES (1, 1, 1)

Step 8: Create Waste from Citizen
   INSERT INTO Waste (name, category, citizen_id) 
   VALUES ('Plastic Bottles', 'Recyclable', 1)

Step 9: Link Waste to Recycling Center
   INSERT INTO Recycling_Center (location, capacity, operating_hours, waste_id) 
   VALUES ('East Center', 1000, '8AM-6PM', 1)

Step 10: Create Bill for Citizen
   INSERT INTO Bill (status, amount, due_date, citizen_id) 
   VALUES ('Pending', 500.00, '2025-12-15', 1)

Step 11: Record Payment
   INSERT INTO Payment (amount, method, payment_date, citizen_id, bill_id) 
   VALUES (500.00, 'Bank Transfer', '2025-11-14', 1, 1)


-- ============================================================================
-- VERIFICATION QUERIES FOR RELATIONSHIPS
-- ============================================================================

-- Check TERNARY 1: Has_Schedule with all 3 tables
SELECT COUNT(*) FROM Has_Schedule hs 
WHERE EXISTS (SELECT 1 FROM Area a WHERE a.area_id = hs.area_id)
  AND EXISTS (SELECT 1 FROM Crew c WHERE c.crew_id = hs.crew_id)
  AND EXISTS (SELECT 1 FROM Collection_Schedule cs WHERE cs.schedule_id = hs.schedule_id);

-- Check TERNARY 2: Assigned with team-crew relationship
SELECT COUNT(*) FROM Assigned a 
WHERE EXISTS (SELECT 1 FROM Area ar WHERE ar.area_id = a.area_id)
  AND EXISTS (SELECT 1 FROM Crew c WHERE c.team_id = a.team_id);

-- Check all Foreign Key constraints are satisfied
SELECT 
    'Citizen → Area' AS relationship,
    COUNT(*) AS count
FROM Citizen c
WHERE NOT EXISTS (SELECT 1 FROM Area a WHERE a.area_id = c.area_id)

UNION ALL

SELECT 
    'Bill → Citizen' AS relationship,
    COUNT(*) AS count
FROM Bill b
WHERE NOT EXISTS (SELECT 1 FROM Citizen c WHERE c.citizen_id = b.citizen_id)

UNION ALL

SELECT 
    'Waste → Citizen' AS relationship,
    COUNT(*) AS count
FROM Waste w
WHERE NOT EXISTS (SELECT 1 FROM Citizen c WHERE c.citizen_id = w.citizen_id)

UNION ALL

SELECT 
    'Bins → Area' AS relationship,
    COUNT(*) AS count
FROM Bins b
WHERE NOT EXISTS (SELECT 1 FROM Area a WHERE a.area_id = b.area_id)

UNION ALL

SELECT 
    'Crew → Area' AS relationship,
    COUNT(*) AS count
FROM Crew c
WHERE NOT EXISTS (SELECT 1 FROM Area a WHERE a.area_id = c.area_id)

UNION ALL

SELECT 
    'Crew → Schedule' AS relationship,
    COUNT(*) AS count
FROM Crew c
WHERE NOT EXISTS (SELECT 1 FROM Collection_Schedule cs WHERE cs.schedule_id = c.schedule_id)

UNION ALL

SELECT 
    'Crew → Team' AS relationship,
    COUNT(*) AS count
FROM Crew c
WHERE NOT EXISTS (SELECT 1 FROM Assigned a WHERE a.team_id = c.team_id);

