-- ============================================================================
-- WASTE MANAGEMENT DATABASE - SQL JOIN QUERIES FOR TERMINAL TESTING
-- ============================================================================
-- Run these queries from terminal with: mysql -u root wasteManagement < SQL_JOIN_QUERIES_TERMINAL.sql
-- Or individual queries with: mysql -u root wasteManagement -e "query here"
-- ============================================================================

USE wasteManagement;

-- ============================================================================
-- SECTION 1: BINARY RELATIONSHIPS - SIMPLE TWO TABLE JOINS
-- ============================================================================

-- ============ QUERY 1.1: Citizens with their assigned Areas =============
-- Shows each citizen and the area they belong to
SELECT 
    '--- QUERY 1.1: Citizens with Areas ---' AS Query_Title;

SELECT 
    c.citizen_id,
    c.name AS citizen_name,
    c.address,
    c.contact,
    a.area_id,
    a.area_name,
    a.description
FROM Citizen c
INNER JOIN Area a ON c.area_id = a.area_id
LIMIT 10;

-- ============ QUERY 1.2: Area Summary with Citizen Count =============
-- Shows each area and count of citizens in that area
SELECT 
    '--- QUERY 1.2: Area Summary with Citizen Count ---' AS Query_Title;

SELECT 
    a.area_id,
    a.area_name,
    COUNT(c.citizen_id) AS total_citizens,
    GROUP_CONCAT(c.name SEPARATOR ', ') AS citizen_names
FROM Area a
LEFT JOIN Citizen c ON a.area_id = c.area_id
GROUP BY a.area_id, a.area_name;

-- ============ QUERY 1.3: Citizens with their Bills =============
-- Shows each bill with citizen information
SELECT 
    '--- QUERY 1.3: Citizens with Bills ---' AS Query_Title;

SELECT 
    b.bill_id,
    b.amount,
    b.status,
    b.due_date,
    c.citizen_id,
    c.name AS citizen_name,
    c.contact
FROM Bill b
INNER JOIN Citizen c ON b.citizen_id = c.citizen_id
LIMIT 10;

-- ============ QUERY 1.4: Citizen Bill Summary =============
-- Shows each citizen with their bill statistics
SELECT 
    '--- QUERY 1.4: Citizen Bill Summary ---' AS Query_Title;

SELECT 
    c.citizen_id,
    c.name,
    COUNT(b.bill_id) AS total_bills,
    SUM(b.amount) AS total_bill_amount,
    COUNT(CASE WHEN b.status = 'Paid' THEN 1 END) AS paid_bills,
    COUNT(CASE WHEN b.status = 'Pending' THEN 1 END) AS pending_bills
FROM Citizen c
LEFT JOIN Bill b ON c.citizen_id = b.citizen_id
GROUP BY c.citizen_id, c.name;

-- ============ QUERY 1.5: Waste Records with Citizen Info =============
-- Shows waste records generated by each citizen
SELECT 
    '--- QUERY 1.5: Waste Records with Citizen Info ---' AS Query_Title;

SELECT 
    w.waste_id,
    w.waste_type,
    w.quantity,
    w.status,
    w.collection_date,
    c.citizen_id,
    c.name AS citizen_name,
    c.address
FROM Waste w
INNER JOIN Citizen c ON w.citizen_id = c.citizen_id
LIMIT 10;

-- ============ QUERY 1.6: Citizen Waste Generation Summary =============
-- Shows each citizen with their waste statistics
SELECT 
    '--- QUERY 1.6: Citizen Waste Generation Summary ---' AS Query_Title;

SELECT 
    c.citizen_id,
    c.name,
    COUNT(w.waste_id) AS total_waste_records,
    SUM(w.quantity) AS total_waste_quantity_kg,
    GROUP_CONCAT(DISTINCT w.waste_type SEPARATOR ', ') AS waste_types,
    COUNT(CASE WHEN w.status = 'Recycled' THEN 1 END) AS recycled_count
FROM Citizen c
LEFT JOIN Waste w ON c.citizen_id = w.citizen_id
GROUP BY c.citizen_id, c.name;

-- ============ QUERY 1.7: Payments with Citizen Info =============
-- Shows all payments with citizen details
SELECT 
    '--- QUERY 1.7: Payments with Citizen Info ---' AS Query_Title;

SELECT 
    p.payment_id,
    p.amount,
    p.method,
    p.payment_date,
    c.citizen_id,
    c.name AS citizen_name,
    c.contact
FROM Payment p
INNER JOIN Citizen c ON p.citizen_id = c.citizen_id
ORDER BY p.payment_date DESC
LIMIT 10;

-- ============ QUERY 1.8: Area with Bins Distribution =============
-- Shows each area with their bins information
SELECT 
    '--- QUERY 1.8: Area with Bins Distribution ---' AS Query_Title;

SELECT 
    a.area_id,
    a.area_name,
    COUNT(b.bin_id) AS total_bins,
    SUM(CASE WHEN b.status = 'Full' THEN 1 ELSE 0 END) AS full_bins,
    SUM(CASE WHEN b.status = 'Empty' THEN 1 ELSE 0 END) AS empty_bins,
    ROUND(AVG(b.fill_level), 2) AS avg_fill_level
FROM Area a
LEFT JOIN Bins b ON a.area_id = b.area_id
GROUP BY a.area_id, a.area_name;

-- ============ QUERY 1.9: Area with Crew Members =============
-- Shows each area with assigned crew members
SELECT 
    '--- QUERY 1.9: Area with Crew Members ---' AS Query_Title;

SELECT 
    a.area_id,
    a.area_name,
    COUNT(c.crew_id) AS total_crew_members,
    GROUP_CONCAT(c.crew_name SEPARATOR ', ') AS crew_names,
    GROUP_CONCAT(c.contact SEPARATOR ', ') AS crew_contacts
FROM Area a
LEFT JOIN Crew c ON a.area_id = c.area_id
GROUP BY a.area_id, a.area_name;

-- ============ QUERY 1.10: Collection Schedules with Area Info =============
-- Shows all collection schedules with area details
SELECT 
    '--- QUERY 1.10: Collection Schedules with Area Info ---' AS Query_Title;

SELECT 
    cs.schedule_id,
    cs.schedule_date,
    a.area_id,
    a.area_name,
    DAYNAME(cs.schedule_date) AS day_of_week
FROM Collection_Schedule cs
INNER JOIN Area a ON cs.area_id = a.area_id
ORDER BY cs.schedule_date DESC
LIMIT 10;

-- ============ QUERY 1.11: Bills with Payments =============
-- Shows bills and their associated payments
SELECT 
    '--- QUERY 1.11: Bills with Payments ---' AS Query_Title;

SELECT 
    b.bill_id,
    b.amount AS bill_amount,
    b.status AS bill_status,
    b.due_date,
    p.payment_id,
    p.amount AS payment_amount,
    p.method,
    p.payment_date,
    (b.amount - COALESCE(SUM(p.amount), 0)) AS remaining_balance
FROM Bill b
LEFT JOIN Payment p ON b.bill_id = p.bill_id
GROUP BY b.bill_id, p.payment_id
LIMIT 15;

-- ============ QUERY 1.12: Waste with Recycling Center Info =============
-- Shows waste records and recycling center information
SELECT 
    '--- QUERY 1.12: Waste with Recycling Center Info ---' AS Query_Title;

SELECT 
    w.waste_id,
    w.waste_type,
    w.quantity,
    w.status,
    rc.center_id,
    rc.location,
    rc.capacity
FROM Waste w
LEFT JOIN Recycling_Center rc ON w.waste_id = rc.waste_id
LIMIT 10;

-- ============================================================================
-- SECTION 2: TERNARY RELATIONSHIPS - THREE TABLE JOINS
-- ============================================================================

-- ============ QUERY 2.1: Has_Schedule - Crew Assignments with Schedules =============
-- Shows which crews are assigned to which areas on which dates
SELECT 
    '--- QUERY 2.1: Has_Schedule (Crew-Area-Schedule) ---' AS Query_Title;

SELECT 
    hs.has_schedule_id,
    a.area_id,
    a.area_name,
    c.crew_id,
    c.crew_name,
    cs.schedule_id,
    cs.schedule_date,
    DAYNAME(cs.schedule_date) AS day_name
FROM Has_Schedule hs
INNER JOIN Area a ON hs.area_id = a.area_id
INNER JOIN Crew c ON hs.crew_id = c.crew_id
INNER JOIN Collection_Schedule cs ON hs.schedule_id = cs.schedule_id
LIMIT 20;

-- ============ QUERY 2.2: Schedule Overview with Crew Assignments =============
-- Shows each schedule with all assigned crews and areas
SELECT 
    '--- QUERY 2.2: Schedule Overview with Crew ---' AS Query_Title;

SELECT 
    cs.schedule_id,
    cs.schedule_date,
    a.area_id,
    a.area_name,
    COUNT(DISTINCT c.crew_id) AS assigned_crews,
    GROUP_CONCAT(DISTINCT c.crew_name SEPARATOR ', ') AS crew_names
FROM Collection_Schedule cs
LEFT JOIN Has_Schedule hs ON cs.schedule_id = hs.schedule_id
LEFT JOIN Area a ON cs.area_id = a.area_id
LEFT JOIN Crew c ON hs.crew_id = c.crew_id
GROUP BY cs.schedule_id, cs.schedule_date, a.area_id, a.area_name
ORDER BY cs.schedule_date DESC;

-- ============ QUERY 2.3: Crew Schedule Details =============
-- Shows each crew member with their assigned schedules and areas
SELECT 
    '--- QUERY 2.3: Crew Schedule Details ---' AS Query_Title;

SELECT 
    c.crew_id,
    c.crew_name,
    c.contact,
    COUNT(DISTINCT hs.has_schedule_id) AS total_assignments,
    GROUP_CONCAT(DISTINCT a.area_name SEPARATOR ', ') AS assigned_areas,
    MIN(cs.schedule_date) AS first_assignment,
    MAX(cs.schedule_date) AS last_assignment
FROM Crew c
LEFT JOIN Has_Schedule hs ON c.crew_id = hs.crew_id
LEFT JOIN Area a ON hs.area_id = a.area_id
LEFT JOIN Collection_Schedule cs ON hs.schedule_id = cs.schedule_id
GROUP BY c.crew_id, c.crew_name, c.contact;

-- ============ QUERY 2.4: Assigned - Teams with Crew Members =============
-- Shows team assignments with crew details in areas
SELECT 
    '--- QUERY 2.4: Assigned (Team-Area-Crew) ---' AS Query_Title;

SELECT 
    assigned.team_id,
    assigned.team_name,
    a.area_id,
    a.area_name,
    c.crew_id,
    c.crew_name,
    c.contact
FROM Assigned assigned
INNER JOIN Area a ON assigned.area_id = a.area_id
INNER JOIN Crew c ON assigned.team_id = c.team_id
LIMIT 20;

-- ============ QUERY 2.5: Area with Teams and Crew Breakdown =============
-- Shows areas with their teams and crew members
SELECT 
    '--- QUERY 2.5: Area with Teams and Crew ---' AS Query_Title;

SELECT 
    a.area_id,
    a.area_name,
    assigned.team_id,
    assigned.team_name,
    COUNT(DISTINCT c.crew_id) AS crew_count,
    GROUP_CONCAT(c.crew_name SEPARATOR ', ') AS crew_members
FROM Area a
LEFT JOIN Assigned assigned ON a.area_id = assigned.area_id
LEFT JOIN Crew c ON assigned.team_id = c.team_id
GROUP BY a.area_id, a.area_name, assigned.team_id, assigned.team_name
ORDER BY a.area_id, assigned.team_id;

-- ============================================================================
-- SECTION 3: COMPLEX MULTI-TABLE JOINS (4+ TABLES)
-- ============================================================================

-- ============ QUERY 3.1: Complete Citizen Profile =============
-- Shows comprehensive information for each citizen
SELECT 
    '--- QUERY 3.1: Complete Citizen Profile ---' AS Query_Title;

SELECT 
    c.citizen_id,
    c.name AS citizen_name,
    c.address,
    c.contact,
    a.area_id,
    a.area_name,
    COUNT(DISTINCT b.bill_id) AS total_bills,
    SUM(DISTINCT b.amount) AS total_bill_amount,
    COUNT(DISTINCT p.payment_id) AS total_payments,
    SUM(DISTINCT p.amount) AS total_paid,
    COUNT(DISTINCT w.waste_id) AS waste_records
FROM Citizen c
LEFT JOIN Area a ON c.area_id = a.area_id
LEFT JOIN Bill b ON c.citizen_id = b.citizen_id
LEFT JOIN Payment p ON c.citizen_id = p.citizen_id
LEFT JOIN Waste w ON c.citizen_id = w.citizen_id
GROUP BY c.citizen_id, c.name, c.address, c.contact, a.area_id, a.area_name
LIMIT 20;

-- ============ QUERY 3.2: Area Operations Overview =============
-- Complete overview of area operations with all related data
SELECT 
    '--- QUERY 3.2: Area Operations Overview ---' AS Query_Title;

SELECT 
    a.area_id,
    a.area_name,
    COUNT(DISTINCT c.citizen_id) AS total_citizens,
    COUNT(DISTINCT b.bill_id) AS total_bills,
    SUM(b.amount) AS total_billing_amount,
    COUNT(DISTINCT cs.schedule_id) AS scheduled_collections,
    COUNT(DISTINCT crew.crew_id) AS crew_members,
    COUNT(DISTINCT bin.bin_id) AS total_bins
FROM Area a
LEFT JOIN Citizen c ON a.area_id = c.area_id
LEFT JOIN Bill b ON c.citizen_id = b.citizen_id
LEFT JOIN Collection_Schedule cs ON a.area_id = cs.area_id
LEFT JOIN Crew crew ON a.area_id = crew.area_id
LEFT JOIN Bins bin ON a.area_id = bin.area_id
GROUP BY a.area_id, a.area_name;

-- ============ QUERY 3.3: Billing and Payment Tracking =============
-- Detailed bill payment status and tracking
SELECT 
    '--- QUERY 3.3: Billing and Payment Tracking ---' AS Query_Title;

SELECT 
    c.citizen_id,
    c.name AS citizen_name,
    b.bill_id,
    b.amount AS bill_amount,
    b.due_date,
    b.status AS bill_status,
    COUNT(p.payment_id) AS payment_count,
    SUM(p.amount) AS total_paid,
    (b.amount - COALESCE(SUM(p.amount), 0)) AS outstanding_amount,
    MAX(p.payment_date) AS last_payment_date
FROM Citizen c
LEFT JOIN Bill b ON c.citizen_id = b.citizen_id
LEFT JOIN Payment p ON b.bill_id = p.bill_id
GROUP BY c.citizen_id, c.name, b.bill_id, b.amount, b.due_date, b.status
ORDER BY c.citizen_id, b.bill_id
LIMIT 20;

-- ============ QUERY 3.4: Waste Collection and Recycling Data =============
-- Comprehensive waste collection and recycling information
SELECT 
    '--- QUERY 3.4: Waste Collection and Recycling ---' AS Query_Title;

SELECT 
    c.citizen_id,
    c.name AS citizen_name,
    a.area_name,
    w.waste_id,
    w.waste_type,
    w.quantity,
    w.status,
    w.collection_date,
    rc.center_id,
    rc.location,
    COUNT(w.waste_id) OVER (PARTITION BY w.waste_type) AS total_waste_type,
    COUNT(w.waste_id) OVER (PARTITION BY w.status) AS total_status_count
FROM Waste w
LEFT JOIN Citizen c ON w.citizen_id = c.citizen_id
LEFT JOIN Area a ON w.area_id = a.area_id
LEFT JOIN Recycling_Center rc ON w.waste_id = rc.waste_id
LIMIT 20;

-- ============ QUERY 3.5: Area Schedule Staffing Report =============
-- Shows which areas have schedules with assigned crew
SELECT 
    '--- QUERY 3.5: Area Schedule Staffing Report ---' AS Query_Title;

SELECT 
    a.area_id,
    a.area_name,
    cs.schedule_id,
    cs.schedule_date,
    COUNT(DISTINCT c.crew_id) AS assigned_crews,
    GROUP_CONCAT(DISTINCT c.crew_name SEPARATOR ', ') AS crew_names,
    GROUP_CONCAT(DISTINCT c.contact SEPARATOR ', ') AS crew_contacts
FROM Area a
LEFT JOIN Collection_Schedule cs ON a.area_id = cs.area_id
LEFT JOIN Has_Schedule hs ON cs.schedule_id = hs.schedule_id AND a.area_id = hs.area_id
LEFT JOIN Crew c ON hs.crew_id = c.crew_id
GROUP BY a.area_id, a.area_name, cs.schedule_id, cs.schedule_date
ORDER BY cs.schedule_date DESC;

-- ============================================================================
-- SECTION 4: AGGREGATE AND STATISTICAL JOINS
-- ============================================================================

-- ============ QUERY 4.1: Payment Method Statistics =============
-- Shows payment statistics by method and citizen area
SELECT 
    '--- QUERY 4.1: Payment Method Statistics ---' AS Query_Title;

SELECT 
    a.area_name,
    p.method,
    COUNT(p.payment_id) AS payment_count,
    SUM(p.amount) AS total_amount,
    ROUND(AVG(p.amount), 2) AS avg_payment
FROM Payment p
LEFT JOIN Citizen c ON p.citizen_id = c.citizen_id
LEFT JOIN Area a ON c.area_id = a.area_id
GROUP BY a.area_name, p.method
ORDER BY a.area_name, total_amount DESC;

-- ============ QUERY 4.2: Waste Statistics by Type and Status =============
-- Statistical breakdown of waste by type and collection status
SELECT 
    '--- QUERY 4.2: Waste Statistics by Type and Status ---' AS Query_Title;

SELECT 
    w.waste_type,
    w.status,
    COUNT(w.waste_id) AS record_count,
    SUM(w.quantity) AS total_quantity_kg,
    ROUND(AVG(w.quantity), 2) AS avg_quantity_kg,
    MIN(w.quantity) AS min_quantity,
    MAX(w.quantity) AS max_quantity,
    a.area_name
FROM Waste w
LEFT JOIN Area a ON w.area_id = a.area_id
GROUP BY w.waste_type, w.status, a.area_name
ORDER BY w.waste_type, w.status;

-- ============ QUERY 4.3: Bill Status Summary by Area =============
-- Bill payment status summary grouped by area
SELECT 
    '--- QUERY 4.3: Bill Status Summary by Area ---' AS Query_Title;

SELECT 
    a.area_name,
    b.status,
    COUNT(b.bill_id) AS bill_count,
    SUM(b.amount) AS total_amount,
    ROUND(AVG(b.amount), 2) AS avg_bill_amount,
    ROUND((COUNT(b.bill_id) / SUM(COUNT(b.bill_id)) OVER (PARTITION BY a.area_name)) * 100, 2) AS percentage
FROM Bill b
LEFT JOIN Citizen c ON b.citizen_id = c.citizen_id
LEFT JOIN Area a ON c.area_id = a.area_id
GROUP BY a.area_name, b.status
ORDER BY a.area_name, total_amount DESC;

-- ============ QUERY 4.4: Crew Productivity Metrics =============
-- Shows crew member activity and assignment frequency
SELECT 
    '--- QUERY 4.4: Crew Productivity Metrics ---' AS Query_Title;

SELECT 
    c.crew_id,
    c.crew_name,
    c.contact,
    a.area_name,
    COUNT(DISTINCT hs.schedule_id) AS total_assignments,
    COUNT(DISTINCT hs.area_id) AS areas_covered,
    MIN(cs.schedule_date) AS earliest_assignment,
    MAX(cs.schedule_date) AS latest_assignment
FROM Crew c
LEFT JOIN Area a ON c.area_id = a.area_id
LEFT JOIN Has_Schedule hs ON c.crew_id = hs.crew_id
LEFT JOIN Collection_Schedule cs ON hs.schedule_id = cs.schedule_id
GROUP BY c.crew_id, c.crew_name, c.contact, a.area_name
ORDER BY total_assignments DESC;

-- ============================================================================
-- SECTION 5: DATA INTEGRITY AND RELATIONSHIP VERIFICATION QUERIES
-- ============================================================================

-- ============ QUERY 5.1: Orphaned Records Check =============
-- Find bills without citizens
SELECT 
    '--- QUERY 5.1: Orphaned Bills (Bills without Citizens) ---' AS Query_Title;

SELECT 
    b.bill_id,
    b.citizen_id,
    b.amount,
    'ORPHANED' AS status
FROM Bill b
WHERE b.citizen_id NOT IN (SELECT citizen_id FROM Citizen)
LIMIT 10;

-- ============ QUERY 5.2: Unused Areas =============
-- Find areas with no citizens assigned
SELECT 
    '--- QUERY 5.2: Unused Areas (No Citizens) ---' AS Query_Title;

SELECT 
    a.area_id,
    a.area_name,
    'NO_CITIZENS' AS status
FROM Area a
LEFT JOIN Citizen c ON a.area_id = c.area_id
WHERE c.citizen_id IS NULL
GROUP BY a.area_id, a.area_name;

-- ============ QUERY 5.3: Relationship Verification Summary =============
-- Summary of all relationships across the database
SELECT 
    '--- QUERY 5.3: Relationship Verification Summary ---' AS Query_Title;

SELECT 
    'Citizens in Areas' AS relationship,
    COUNT(DISTINCT c.citizen_id) AS linked_records
FROM Citizen c
WHERE c.area_id IS NOT NULL
UNION ALL
SELECT 
    'Crew in Areas',
    COUNT(DISTINCT crew.crew_id)
FROM Crew crew
WHERE crew.area_id IS NOT NULL
UNION ALL
SELECT 
    'Bills to Citizens',
    COUNT(DISTINCT bill.bill_id)
FROM Bill bill
WHERE bill.citizen_id IS NOT NULL
UNION ALL
SELECT 
    'Waste Records',
    COUNT(DISTINCT w.waste_id)
FROM Waste w
WHERE w.citizen_id IS NOT NULL
UNION ALL
SELECT 
    'Payments Made',
    COUNT(DISTINCT p.payment_id)
FROM Payment p
WHERE p.citizen_id IS NOT NULL
UNION ALL
SELECT 
    'Has_Schedule Assignments',
    COUNT(DISTINCT hs.has_schedule_id)
FROM Has_Schedule hs
UNION ALL
SELECT 
    'Assigned Team Members',
    COUNT(DISTINCT asn.team_id)
FROM Assigned asn;

-- ============================================================================
-- END OF SQL JOIN QUERIES
-- ============================================================================
