-- ============================================================================
-- WASTE MANAGEMENT DATABASE - TABLE RELATIONSHIPS & JOINs
-- ============================================================================
-- This file contains all relationship queries based on the database schema
-- Including 2 ternary relationships: Has_Schedule and Assigned

USE wasteManagemet;

-- ============================================================================
-- SECTION 1: IDENTIFY RELATIONSHIPS
-- ============================================================================
/*
PRIMARY RELATIONSHIPS (Binary - between 2 tables):
1. Citizen → Area (Many-to-One)
2. Citizen → Bill (One-to-Many)
3. Citizen → Waste (One-to-Many)
4. Citizen → Payment (One-to-Many)
5. Area → Bins (One-to-Many)
6. Area → Crew (One-to-Many)
7. Area → Collection_Schedule (One-to-Many)
8. Area → Assigned (One-to-Many)
9. Bill → Payment (One-to-Many)
10. Waste → Recycling_Center (One-to-Many)

TERNARY RELATIONSHIPS (between 3+ tables):
1. Has_Schedule: Area ↔ Crew ↔ Collection_Schedule (Junction Table)
   - Links crew assignments to areas with specific collection schedules
2. Assigned: Crew ↔ Area ↔ Team (Junction Table)
   - Links crews to areas and team assignments
*/

-- ============================================================================
-- SECTION 2: SIMPLE BINARY RELATIONSHIPS
-- ============================================================================

-- ============ RELATIONSHIP 1: Citizen ↔ Area =============
-- Get all citizens in a specific area with area details
SELECT 
    c.citizen_id,
    c.name AS citizen_name,
    c.address,
    c.contact,
    a.area_id,
    a.area_name,
    a.description
FROM Citizen c
INNER JOIN Area a ON c.area_id = a.area_id;

-- Get area with all its citizens
SELECT 
    a.area_id,
    a.area_name,
    COUNT(c.citizen_id) AS total_citizens,
    GROUP_CONCAT(c.name SEPARATOR ', ') AS citizen_names
FROM Area a
LEFT JOIN Citizen c ON a.area_id = c.area_id
GROUP BY a.area_id, a.area_name;


-- ============ RELATIONSHIP 2: Citizen ↔ Bill =============
-- Get bills for a specific citizen with citizen details
SELECT 
    b.bill_id,
    b.status,
    b.amount,
    b.due_date,
    c.citizen_id,
    c.name AS citizen_name,
    c.contact
FROM Bill b
INNER JOIN Citizen c ON b.citizen_id = c.citizen_id;

-- Get citizen with all their bills
SELECT 
    c.citizen_id,
    c.name,
    COUNT(b.bill_id) AS total_bills,
    SUM(b.amount) AS total_bill_amount,
    GROUP_CONCAT(CONCAT('Bill#', b.bill_id, '(', b.status, ')') SEPARATOR ', ') AS bill_details
FROM Citizen c
LEFT JOIN Bill b ON c.citizen_id = b.citizen_id
GROUP BY c.citizen_id, c.name;


-- ============ RELATIONSHIP 3: Citizen ↔ Waste =============
-- Get waste records generated by a citizen
SELECT 
    w.waste_id,
    w.name AS waste_type,
    w.category,
    c.citizen_id,
    c.name AS citizen_name,
    c.address
FROM Waste w
INNER JOIN Citizen c ON w.citizen_id = c.citizen_id;

-- Get citizen with their waste generation history
SELECT 
    c.citizen_id,
    c.name,
    COUNT(w.waste_id) AS total_waste_items,
    GROUP_CONCAT(DISTINCT w.category SEPARATOR ', ') AS waste_categories
FROM Citizen c
LEFT JOIN Waste w ON c.citizen_id = w.citizen_id
GROUP BY c.citizen_id, c.name;


-- ============ RELATIONSHIP 4: Citizen ↔ Payment =============
-- Get all payments made by a citizen
SELECT 
    p.payment_id,
    p.amount,
    p.method,
    p.payment_date,
    c.citizen_id,
    c.name AS citizen_name,
    c.contact
FROM Payment p
INNER JOIN Citizen c ON p.citizen_id = c.citizen_id
ORDER BY p.payment_date DESC;

-- Get citizen payment summary
SELECT 
    c.citizen_id,
    c.name,
    COUNT(p.payment_id) AS total_payments,
    SUM(p.amount) AS total_paid_amount,
    GROUP_CONCAT(DISTINCT p.method SEPARATOR ', ') AS payment_methods
FROM Citizen c
LEFT JOIN Payment p ON c.citizen_id = p.citizen_id
GROUP BY c.citizen_id, c.name;


-- ============ RELATIONSHIP 5: Area ↔ Bins =============
-- Get all bins in a specific area
SELECT 
    b.bin_id,
    b.status,
    b.fill_level,
    b.sensor,
    a.area_id,
    a.area_name
FROM Bins b
INNER JOIN Area a ON b.area_id = a.area_id;

-- Get area with bin distribution
SELECT 
    a.area_id,
    a.area_name,
    COUNT(b.bin_id) AS total_bins,
    SUM(CASE WHEN b.status = 'Full' THEN 1 ELSE 0 END) AS full_bins,
    SUM(CASE WHEN b.status = 'Empty' THEN 1 ELSE 0 END) AS empty_bins,
    AVG(b.fill_level) AS avg_fill_level
FROM Area a
LEFT JOIN Bins b ON a.area_id = b.area_id
GROUP BY a.area_id, a.area_name;


-- ============ RELATIONSHIP 6: Area ↔ Crew =============
-- Get all crew members assigned to a specific area
SELECT 
    c.crew_id,
    c.crew_name,
    c.contact,
    a.area_id,
    a.area_name
FROM Crew c
INNER JOIN Area a ON c.area_id = a.area_id;

-- Get area with crew details
SELECT 
    a.area_id,
    a.area_name,
    COUNT(c.crew_id) AS total_crew_members,
    GROUP_CONCAT(c.crew_name SEPARATOR ', ') AS crew_members
FROM Area a
LEFT JOIN Crew c ON a.area_id = c.area_id
GROUP BY a.area_id, a.area_name;


-- ============ RELATIONSHIP 7: Area ↔ Collection_Schedule =============
-- Get all collection schedules for a specific area
SELECT 
    cs.schedule_id,
    cs.schedule_date,
    a.area_id,
    a.area_name
FROM Collection_Schedule cs
INNER JOIN Area a ON cs.area_id = a.area_id
ORDER BY cs.schedule_date;

-- Get area with scheduled collections
SELECT 
    a.area_id,
    a.area_name,
    COUNT(cs.schedule_id) AS total_schedules,
    MIN(cs.schedule_date) AS first_collection,
    MAX(cs.schedule_date) AS last_collection
FROM Area a
LEFT JOIN Collection_Schedule cs ON a.area_id = cs.area_id
GROUP BY a.area_id, a.area_name;


-- ============ RELATIONSHIP 8: Area ↔ Assigned (Teams) =============
-- Get all teams assigned to a specific area
SELECT 
    a_team.team_id,
    a_team.team_name,
    a.area_id,
    a.area_name
FROM Assigned a_team
INNER JOIN Area a ON a_team.area_id = a.area_id;

-- Get area with assigned teams
SELECT 
    a.area_id,
    a.area_name,
    COUNT(a_team.team_id) AS total_teams,
    GROUP_CONCAT(a_team.team_name SEPARATOR ', ') AS team_names
FROM Area a
LEFT JOIN Assigned a_team ON a.area_id = a_team.area_id
GROUP BY a.area_id, a.area_name;


-- ============ RELATIONSHIP 9: Bill ↔ Payment =============
-- Get all payments related to a specific bill
SELECT 
    b.bill_id,
    b.status,
    b.amount AS bill_amount,
    b.due_date,
    p.payment_id,
    p.amount AS payment_amount,
    p.method,
    p.payment_date
FROM Bill b
LEFT JOIN Payment p ON b.bill_id = p.bill_id;

-- Get bill payment summary
SELECT 
    b.bill_id,
    b.status,
    b.amount AS bill_amount,
    COUNT(p.payment_id) AS total_payments,
    SUM(p.amount) AS total_paid,
    (b.amount - COALESCE(SUM(p.amount), 0)) AS remaining_balance
FROM Bill b
LEFT JOIN Payment p ON b.bill_id = p.bill_id
GROUP BY b.bill_id, b.status, b.amount;


-- ============ RELATIONSHIP 10: Waste ↔ Recycling_Center =============
-- Get recycling centers handling specific waste types
SELECT 
    w.waste_id,
    w.name AS waste_type,
    w.category,
    rc.center_id,
    rc.location,
    rc.capacity
FROM Waste w
LEFT JOIN Recycling_Center rc ON w.waste_id = rc.waste_id;

-- Get recycling center with waste details
SELECT 
    rc.center_id,
    rc.location,
    rc.capacity,
    COUNT(w.waste_id) AS total_waste_items,
    GROUP_CONCAT(DISTINCT w.category SEPARATOR ', ') AS waste_categories
FROM Recycling_Center rc
LEFT JOIN Waste w ON rc.waste_id = w.waste_id
GROUP BY rc.center_id, rc.location, rc.capacity;


-- ============================================================================
-- SECTION 3: TERNARY RELATIONSHIPS (3+ tables)
-- ============================================================================

-- ============ TERNARY RELATIONSHIP 1: Has_Schedule (Area ↔ Crew ↔ Collection_Schedule) =============
-- Get crew assignments with their collection schedules in specific areas
SELECT 
    hs.has_schedule_id,
    a.area_id,
    a.area_name,
    c.crew_id,
    c.crew_name,
    cs.schedule_id,
    cs.schedule_date
FROM Has_Schedule hs
INNER JOIN Area a ON hs.area_id = a.area_id
INNER JOIN Crew c ON hs.crew_id = c.crew_id
INNER JOIN Collection_Schedule cs ON hs.schedule_id = cs.schedule_id;

-- Get all crew assignments with their schedules in each area
SELECT 
    a.area_id,
    a.area_name,
    c.crew_id,
    c.crew_name,
    COUNT(hs.schedule_id) AS assigned_schedules,
    MIN(cs.schedule_date) AS first_schedule,
    MAX(cs.schedule_date) AS last_schedule
FROM Area a
LEFT JOIN Has_Schedule hs ON a.area_id = hs.area_id
LEFT JOIN Crew c ON hs.crew_id = c.crew_id
LEFT JOIN Collection_Schedule cs ON hs.schedule_id = cs.schedule_id
GROUP BY a.area_id, a.area_name, c.crew_id, c.crew_name
ORDER BY a.area_id, c.crew_id;

-- Get schedule details with crew and area information
SELECT 
    cs.schedule_id,
    cs.schedule_date,
    a.area_id,
    a.area_name,
    GROUP_CONCAT(c.crew_name SEPARATOR ', ') AS assigned_crews
FROM Collection_Schedule cs
LEFT JOIN Has_Schedule hs ON cs.schedule_id = hs.schedule_id
LEFT JOIN Area a ON cs.area_id = a.area_id
LEFT JOIN Crew c ON hs.crew_id = c.crew_id
GROUP BY cs.schedule_id, cs.schedule_date, a.area_id, a.area_name
ORDER BY cs.schedule_date;


-- ============ TERNARY RELATIONSHIP 2: Assigned (Crew ↔ Area ↔ Team) =============
-- Get crew members assigned to teams in specific areas
SELECT 
    a_team.team_id,
    a_team.team_name,
    a.area_id,
    a.area_name,
    c.crew_id,
    c.crew_name,
    c.contact
FROM Assigned a_team
INNER JOIN Area a ON a_team.area_id = a.area_id
INNER JOIN Crew c ON a_team.team_id = c.team_id;

-- Get area with teams and their crew members
SELECT 
    a.area_id,
    a.area_name,
    a_team.team_id,
    a_team.team_name,
    COUNT(c.crew_id) AS crew_count,
    GROUP_CONCAT(c.crew_name SEPARATOR ', ') AS crew_members
FROM Area a
LEFT JOIN Assigned a_team ON a.area_id = a_team.area_id
LEFT JOIN Crew c ON a_team.team_id = c.team_id
GROUP BY a.area_id, a.area_name, a_team.team_id, a_team.team_name
ORDER BY a.area_id, a_team.team_id;

-- Get team composition with area assignments
SELECT 
    a_team.team_id,
    a_team.team_name,
    a.area_id,
    a.area_name,
    COUNT(c.crew_id) AS total_members,
    GROUP_CONCAT(CONCAT(c.crew_name, '(', c.contact, ')') SEPARATOR '; ') AS crew_details
FROM Assigned a_team
LEFT JOIN Area a ON a_team.area_id = a.area_id
LEFT JOIN Crew c ON a_team.team_id = c.team_id
GROUP BY a_team.team_id, a_team.team_name, a.area_id, a.area_name
ORDER BY a_team.team_id, a.area_id;


-- ============================================================================
-- SECTION 4: COMPLEX MULTI-TABLE JOINS
-- ============================================================================

-- ============ Complex Join 1: Complete Citizen Profile =============
-- Get complete information about a citizen including area, bills, payments, and waste
SELECT 
    c.citizen_id,
    c.name AS citizen_name,
    c.address,
    c.contact,
    a.area_id,
    a.area_name,
    COUNT(DISTINCT b.bill_id) AS total_bills,
    SUM(b.amount) AS total_bill_amount,
    COUNT(DISTINCT p.payment_id) AS total_payments,
    SUM(p.amount) AS total_paid,
    COUNT(DISTINCT w.waste_id) AS waste_records
FROM Citizen c
LEFT JOIN Area a ON c.area_id = a.area_id
LEFT JOIN Bill b ON c.citizen_id = b.citizen_id
LEFT JOIN Payment p ON c.citizen_id = p.citizen_id
LEFT JOIN Waste w ON c.citizen_id = w.citizen_id
GROUP BY c.citizen_id, c.name, c.address, c.contact, a.area_id, a.area_name;


-- ============ Complex Join 2: Area Operations Overview =============
-- Get complete overview of area operations
SELECT 
    a.area_id,
    a.area_name,
    COUNT(DISTINCT c.citizen_id) AS total_citizens,
    COUNT(DISTINCT b.bin_id) AS total_bins,
    COUNT(DISTINCT crew.crew_id) AS total_crew,
    COUNT(DISTINCT cs.schedule_id) AS total_schedules,
    SUM(b.fill_level) / COUNT(DISTINCT b.bin_id) AS avg_bin_fill_level
FROM Area a
LEFT JOIN Citizen c ON a.area_id = c.area_id
LEFT JOIN Bins b ON a.area_id = b.area_id
LEFT JOIN Crew crew ON a.area_id = crew.area_id
LEFT JOIN Collection_Schedule cs ON a.area_id = cs.area_id
GROUP BY a.area_id, a.area_name;


-- ============ Complex Join 3: Bill-Payment Tracking =============
-- Track which bills are paid and which need follow-up
SELECT 
    c.citizen_id,
    c.name AS citizen_name,
    c.contact,
    b.bill_id,
    b.status,
    b.amount AS bill_amount,
    b.due_date,
    SUM(p.amount) AS total_paid,
    (b.amount - COALESCE(SUM(p.amount), 0)) AS outstanding,
    CASE 
        WHEN b.status = 'Paid' THEN 'Complete'
        WHEN b.due_date < CURDATE() THEN 'Overdue'
        ELSE 'Pending'
    END AS payment_status
FROM Bill b
INNER JOIN Citizen c ON b.citizen_id = c.citizen_id
LEFT JOIN Payment p ON b.bill_id = p.bill_id
GROUP BY b.bill_id, c.citizen_id, c.name, c.contact, b.status, b.amount, b.due_date
ORDER BY b.due_date;


-- ============ Complex Join 4: Waste Management Chain =============
-- Track waste from citizen through recycling center
SELECT 
    c.citizen_id,
    c.name AS citizen_name,
    w.waste_id,
    w.name AS waste_type,
    w.category,
    rc.center_id,
    rc.location AS recycling_center,
    rc.capacity,
    rc.operating_hours
FROM Citizen c
INNER JOIN Waste w ON c.citizen_id = w.citizen_id
LEFT JOIN Recycling_Center rc ON w.waste_id = rc.waste_id;


-- ============ Complex Join 5: Crew Assignment and Schedule =============
-- Get crew assignments with their areas and all associated schedules
SELECT 
    crew.crew_id,
    crew.crew_name,
    crew.contact,
    a_team.team_id,
    a_team.team_name,
    area.area_id,
    area.area_name,
    cs.schedule_id,
    cs.schedule_date,
    hs.has_schedule_id
FROM Crew crew
LEFT JOIN Assigned a_team ON crew.team_id = a_team.team_id
LEFT JOIN Area area ON a_team.area_id = area.area_id
LEFT JOIN Has_Schedule hs ON crew.crew_id = hs.crew_id AND area.area_id = hs.area_id
LEFT JOIN Collection_Schedule cs ON hs.schedule_id = cs.schedule_id
ORDER BY crew.crew_id, cs.schedule_date;


-- ============================================================================
-- SECTION 5: AGGREGATE & ANALYTICAL QUERIES
-- ============================================================================

-- Get detailed statistics by area
SELECT 
    a.area_id,
    a.area_name,
    COUNT(DISTINCT c.citizen_id) AS citizens,
    COUNT(DISTINCT b.bin_id) AS bins,
    COUNT(DISTINCT b2.bill_id) AS total_bills,
    SUM(b2.amount) AS total_bill_value,
    COUNT(DISTINCT crew.crew_id) AS crew_members,
    COUNT(DISTINCT cs.schedule_id) AS collection_schedules
FROM Area a
LEFT JOIN Citizen c ON a.area_id = c.area_id
LEFT JOIN Bins b ON a.area_id = b.area_id
LEFT JOIN Bill b2 ON c.citizen_id = b2.citizen_id
LEFT JOIN Crew crew ON a.area_id = crew.area_id
LEFT JOIN Collection_Schedule cs ON a.area_id = cs.area_id
GROUP BY a.area_id, a.area_name
ORDER BY a.area_id;
